# Generated by Django 2.0.3 on 2018-03-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('imdb', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
